In [4]:
import numpy as np 
import pandas as pd

**Creating A DataFrame**

In [6]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age' : [28,34,29,42],
    'City' : ['New yourk', 'Paris', 'Berlin', 'London'], 
    'Salary' : [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age       City  Salary
0   John   28  New yourk   65000
1   Anna   34      Paris   70000
2  Peter   29     Berlin   62000
3  Linda   42     London   85000

In [62]:
data_list = [
    ['John', 28, 'New York', 65000], 
    ['Anna', 34, 'Paris', 70000], 
    ['Peter', 29, 'Berlin', 62000], 
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)

In [63]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [64]:
coloumns = ["Name", "age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns = coloumns)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection And Indexing Of Coloumns**

In [65]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [66]:
df2["City"]

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [67]:
df2[["Name", "City", "age"]]

    Name      City  age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

**Creating A new Coloumn**

In [68]:
df2["Designation"] = ["Doctor", "Engg", "Doctor", "Engg"]
df2

    Name  age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Engg
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Engg

**Removing Coloumns**

In [69]:
#Delete a Copy of Coloumn. 
df2.drop("Designation", axis=1)
df2

    Name  age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Engg
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Engg

In [70]:
#Delete Coloumn peranently 
df2.drop("Designation", axis=1, inplace=True)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [71]:
#Delete Multiple ccoloumns 
df2.drop(["Salary", "City" ], axis=1)

    Name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [73]:
df2.index

RangeIndex(start=0, stop=4, step=1)

In [74]:
#Delete a copy of Row. 
df2.drop(3,axis=0)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [75]:
#Delete row permanently
df2.drop(3, axis=0, inplace=True)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [77]:
#Delete multiple rows 
df2.drop(, axis=0)
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

**Selecting Rows**

In [80]:
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [81]:
df2.loc[0]

Name          John
age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [84]:
df2.loc[[0,1]]

   Name  age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

**Selecting Subset Of Rows And Coloumns**

In [90]:
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [85]:
df2.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [89]:
df2.loc[[1,2]][["Name", "age"]]

    Name  age
1   Anna   34
2  Peter   29

**Conditional Selection**

In [91]:
df2

    Name  age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [92]:
#I want to only see those whose age is about 30
df2[df2["age"] > 30]

   Name  age   City  Salary
1  Anna   34  Paris   70000

In [103]:
df2[(df2["age"] > 30) & (df2["City"] == 'Paris')]

   Name  age   City  Salary
1  Anna   34  Paris   70000