In [4]:
import numpy as np 
import pandas as pd

**MERGING DATAFRAMES**

In [5]:
# DataFrame 1: Employee Details
employees = pd.DataFrame({
    'employee_id': [101, 102, 103, 104],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'department': ['IT', 'HR', 'IT', 'Finance']
})
# DataFrame 2: Employee Salaries
salaries = pd.DataFrame({
    'employee_id': [101, 102, 103, 105],
    'salary': [85000, 70000, 90000, 95000]
})

In [12]:
employees

   employee_id     name department
0          101    Alice         IT
1          102      Bob         HR
2          103  Charlie         IT
3          104    David    Finance

In [11]:
salaries

   employee_id  salary
0          101   85000
1          102   70000
2          103   90000
3          105   95000

In [13]:
pd.merge(employees, salaries)

   employee_id     name department  salary
0          101    Alice         IT   85000
1          102      Bob         HR   70000
2          103  Charlie         IT   90000

In [16]:
pd.merge(employees, salaries, on="employee_id", how = "inner")

   employee_id     name department  salary
0          101    Alice         IT   85000
1          102      Bob         HR   70000
2          103  Charlie         IT   90000

In [17]:
pd.merge(employees, salaries, on="employee_id", how = "outer")

   employee_id     name department   salary
0          101    Alice         IT  85000.0
1          102      Bob         HR  70000.0
2          103  Charlie         IT  90000.0
3          104    David    Finance      NaN
4          105      NaN        NaN  95000.0

In [18]:
pd.merge(employees, salaries, on="employee_id", how = "left")

   employee_id     name department   salary
0          101    Alice         IT  85000.0
1          102      Bob         HR  70000.0
2          103  Charlie         IT  90000.0
3          104    David    Finance      NaN

In [19]:
pd.merge(employees, salaries, on="employee_id", how = "right")

   employee_id     name department  salary
0          101    Alice         IT   85000
1          102      Bob         HR   70000
2          103  Charlie         IT   90000
3          105      NaN        NaN   95000

**CONCATINATION OF 2 DATAFRAMES**

In [21]:
# DataFrames from the image
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2"],
        "B": ["B0", "B1", "B2"],
        "C": ["C0", "C1", "C2"],
    }
)

df2 = pd.DataFrame(
    {
        "A": ["A3", "A4", "A5"],
        "B": ["B3", "B4", "B5"],
        "C": ["C3", "C4", "C5"],
    }
)

In [22]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [23]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
#Cocatination on the basis of olumns
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [27]:
#Concatination on the basis of rpow
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**JOINING OF 2 DATAFRAMES**

In [28]:
df1 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "score": [85, 90, 75]
}, index=[2, 3, 4])

In [29]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [30]:
df2

   score
2     85
3     90
4     75

In [31]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [32]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [40]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0