In [2]:
import numpy as np 
import pandas as pd

**DataFrame Basic Operations**

In [3]:
df1 = pd.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "B": [10, 20, 30, 40, 50],
        "C": [100, 200, 300, 400, 500]
    })

In [6]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [7]:
df1.shape

(5, 3)

In [8]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

**DataFrame Applying Functions**

In [9]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500