In [74]:
import numpy as np
import pandas as pd

In [75]:
#Loading the data 
df = pd.read_csv(r'anime.csv')

In [76]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [77]:
df.loc[2]

Rank                                                     3
Title    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
Score                                                 9.06
Name: 2, dtype: object

In [78]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [79]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if i == ")":
            check = False
            return data
        if check == True:
            data = data + i
        if i == "(":
            check = True

In [80]:
df['Episodes'] = df["Title"].apply(extract_episodes)
df.loc[4]['Episodes']

'10 eps'

In [81]:
# Remove Extra space and eps
df['Episodes']  = df['Episodes'].str.replace(" eps","")

In [82]:
#Convert Episode in integer 
df['Episodes'] = df['Episodes'].astype(int)

In [83]:
def extract_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1, i+20):
                data += txt[j]
                
            return data

In [84]:
df['Total Time'] = df['Title'].apply(extract_time)

In [85]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [88]:
# 1. Split the 'Total Time' string into temporary 'start' and 'end' strings
split_dates = df['Total Time'].str.split(' - ', expand=True)

# 2. Convert both columns to pandas datetime objects
start_dt = pd.to_datetime(split_dates[0], format='%b %Y')
end_dt = pd.to_datetime(split_dates[1], format='%b %Y')

# 3. Calculate the difference in months
df['Total Months'] = ((end_dt.dt.year - start_dt.dt.year) * 12 + 
                      (end_dt.dt.month - start_dt.dt.month) + 1)

In [90]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [92]:
# Highest Score:
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,Episodes,Total Time,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [101]:
df['Score'].head()

0    9.10
1    9.07
2    9.06
3    9.06
4    9.05
Name: Score, dtype: float64

In [102]:
# top 5 highest scoring anime
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: object

In [103]:
# anime has the highrst episode count
df[df['Episodes'] == df['Episodes'].max()]

,Rank,Title,Score,Episodes,Total Time,Total Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [111]:
# Sort the DataFrame by 'Episodes' in descending order and select the top 5
top_5_episodes = df.nlargest(5, 'Episodes')

# Display the rank, title, and episode count
print(top_5_episodes[['Rank', 'Title', 'Episodes']])

    Rank                                              Title  Episodes
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...       201
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...       148
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...       110
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...        75
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...        74

In [110]:
# Find the row with the maximum number of months
longest_running_anime = df.loc[df['Total Months'].idxmax()]

# Display the title and the duration
print(f"Longest running anime: {longest_running_anime ['Title']}")
print(f"Duration: {longest_running_anime['Total Months']} months")

Longest running anime: Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Mar 1997309,193 members
Duration: 111 months

In [86]:
# Make a new column for episode count
# Make a new column for time stamp
# Which anime has the highest score
# Give me top 5 highest scoring anime
# Which anime has the highrst episode count
# Animes with top 5 episode count
# Which is the longest running anime